---
- name: Install prerequisites
  hosts: nodes
  become: true

  tasks:

    - name: Install packages apt
      ansible.builtin.apt:
        name: docker

    - name: Install packages snap
      community.general.snap:
        name:
          - go
          - kubectl
        classic: true

    - name: Install kind (go)
      ansible.builtin.command:
        cmd: go install sigs.k8s.io/kind@v0.17.0
      changed_when: true

    - name: Create symlink for kind
      ansible.builtin.command:
        cmd: ln -s /root/go/bin/kind /usr/local/bin/kind
        creates: /usr/local/bin/kind
      changed_when: true

    - name: Copy helper script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/micahculpepper/dockerveth/master/dockerveth.sh
        dest: /root/kandi-kubernetes/
        mode: "744"
